### ISSUE TITLE
Library documentation is empty

### ISSUE THREAD

**Issue by nex3** [dart-lang/stream_transform#89] opened 2019-11-23 21:33 UTC
The dartdoc.org documentation for this library displays no documentation at all: https://pub.dev/documentation/stream_transform/1.0.0/stream_transform/stream_transform-library.html

**Comment by natebosch** [comment] 2019-11-26 23:28
Caused by https://github.com/dart-lang/dartdoc/issues/2032

Should be resolved once the pub site upgrades to a new enough dartdoc.

I was unsure about publishing before the pub site worked, in the end I decided it wasn't worth waiting.

**Comment by natebosch** [comment] 2019-12-26 20:26
Fixed with the latest version of the pub site.

**Closed by natebosch** 2019-12-26 20:26 UTC
